POST http://localhost:5000/api/custom
Content-Type: application/json

{
    "longUrl": "https://www.amazon.com/dp/B089KTZGBC/ref=sspa_dk_detail_1?psc=1&pd_rd_i=B089KTZGBC&pd_rd_w=pX1iF&pf_rd_p=48d372c1-f7e1-4b8b-9d02-4bd86f5158c5&pd_rd_wg=UkNIC&pf_rd_r=AGFKMM1RMQVZ4J05YV0C&pd_rd_r=335f3f2d-1e7f-4e49-92ca-fb006cee9863&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExVEg0RjRST0I5NEVNJmVuY3J5cHRlZElkPUEwMzMzNDQ2MUsyUzNBVVNIQTVPUSZlbmNyeXB0ZWRBZElkPUEwMjc1NzU1MVIzVFJJNDdCRlRZWiZ3aWRnZXROYW1lPXNwX2RldGFpbCZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=",
    "code": "hiring"
}