POST https://shortt-ly.herokuapp.com/api/custom
Content-Type: application/json

{
    "longUrl": "https://drive.google.com/file/d/1Ewhuq6MFHF0e2mHfx9JIBDwANMQcICPP/view?usp=sharing",
    "code": "resume"
}